#!/bin/bash

set -eux

# Install gitrepo for OpenDaylight
sudo git clone https://github.com/dfarrell07/puppet-opendaylight/ /usr/share/openstack-puppet/modules/opendaylight

sudo git clone -b stable/liberty https://github.com/openstack/networking-odl.git /tmp/networking-odl
sudo mv /tmp/networking-odl/networking_odl /usr/lib/python2.7/site-packages/
