#!/bin/bash

set -eux

# Install repo file for OpenDaylight
sudo curl -o/etc/yum.repos.d/opendaylight-3-candidate.repo https://raw.githubusercontent.com/opendaylight/integration-packaging/master/rpm/example_repo_configs/opendaylight-3-candidate.repo

